CREATE DATABASE ToDoList;

USE ToDoList;

CREATE TABLE User(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Login VARCHAR(100) NOT NULL,
    Password VARCHAR(200) NOT NULL
);

CREATE TABLE ToDo(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Text VARCHAR(255) NOT NULL
);